import { Device } from "../types/devices.ts";

export const devices: Device[] = [
    {
        ip: "192.168.0.2",
        mac: "00:1A:2B:3C:4D:5E",
        hostname: "Workstation-01",
        status: "online",
        ping: "24 ms",
        vendor: "Dell",
        interface: "eth0",
        os: "Windows 10",
        uptime: "12h 34m",
        lastSeen: "2 minutes ago",
        openPorts: [22, 80, 443],
    },
    {
        ip: "192.168.0.3",
        mac: "00:1A:2B:3C:4D:5F",
        hostname: "Printer",
        status: "offline",
        ping: "-",
        vendor: "HP",
        interface: "wlan0",
        os: "Firmware 2.1",
        uptime: "-",
        lastSeen: "10 minutes ago",
        openPorts: [80],
    },
    {
        ip: "192.168.0.10",
        mac: "00:1A:2B:3C:4D:60",
        hostname: "Laptop-John",
        status: "online",
        ping: "18 ms",
        vendor: "Apple",
        interface: "wlan0",
        os: "macOS Ventura",
        uptime: "5h 12m",
        lastSeen: "Just now",
        openPorts: [22, 443],
    },
    {
        ip: "192.168.0.15",
        mac: "00:1A:2B:3C:4D:61",
        hostname: "Smart-TV",
        status: "offline",
        ping: "-",
        vendor: "Samsung",
        interface: "wlan0",
        os: "Tizen OS",
        uptime: "-",
        lastSeen: "15 minutes ago",
        openPorts: [],
    },
];

